

ARG REACT_APP_MWS_BRANDING_TITLE="nLab"
ARG REACT_APP_MWS_BRANDING_URL="https://ncatlab.org/nlab/show/HomePage"
ARG REACT_APP_THEME_NR=1
ARG REACT_APP_MWS_MODE=API

ARG REACT_APP_LATEXML_URL=http://localhost:8080
ARG REACT_APP_MWSAPI_URL=http://localhost:3001
ARG REACT_APP_MWS_URL=http://localhost:9090

FROM node:12.6.0-alpine AS builder
WORKDIR /app
COPY . ./

ARG SYMBOLS_PATH=""
ARG EXAMPLE_PATH=""

# copy the example/ symbols json if it is provided
RUN ["$SYMBOLS_PATH" == ""] || COPY $SYMBOLS_PATH ./src/config/symbols.json
RUN ["$EXAMPLE_PATH" == ""] || COPY $SYMBOLS_PATH ./src/config/examples.json
ARG REACT_APP_MWS_BRANDING_TITLE
ARG REACT_APP_MWS_BRANDING_URL
ARG REACT_APP_THEME_NR
ARG REACT_APP_MWS_MODE
ARG REACT_APP_LATEXML_URL
ARG REACT_APP_MWSAPI_URL
ARG REACT_APP_MWS_URL


RUN yarn && yarn build

FROM node:12.6.0-alpine

ARG REACT_APP_MWS_MODE
ARG REACT_APP_LATEXML_URL
ARG REACT_APP_MWSAPI_URL
ARG REACT_APP_MWS_URL

ENV REACT_APP_MWS_MODE=$REACT_APP_MWS_MODE
ENV REACT_APP_LATEXML_URL=$REACT_APP_LATEXML_URL
ENV REACT_APP_MWSAPI_URL=$REACT_APP_MWSAPI_URL
ENV REACT_APP_MWS_URL=$REACT_APP_MWS_URL

ENV NODE_PORT=3000

WORKDIR /app
RUN mkdir -p /app/src
RUN mkdir -p /app/build
COPY --from=builder /app/build /app/build
RUN npm install express http-proxy-middleware
COPY ./express.js .
COPY ./src/setupProxy.js ./src/

CMD ["node", "express.js"]
EXPOSE $NODE_PORT
